export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const USER_SAVED_SUCCESS = "USER_SAVED_SUCCESS";

export const FETCH_ROLES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const ROLES_SUCCESS = "LANGUAGES_SUCCESS";
export const ROLES_FAILURE = "LANGUAGES_FAILURE";
